###################################################################
# PluginAnalyse v1.2                                              #
# made by HackV0gel                                               #
# download: https://github.com/PublicCode1337/PluginAnalyse       #
# discord: https://dsc.gg/bka                                     #
###################################################################

block-ethanol: true
discord-webhook-url: "YOUR DISCORD WEBHOOK HERE!"
