name: PluginAnalyse
version: 1.0-SNAPSHOT
main: de.hackv0gel.pluginAnalyse.PluginAnalyse
commands:
  analyse:
    description: Analyzes packets
    usage: /analyse <view|clear|credits|checkethanol>
  analyse-credits:
    description: Display the Credits from the Developer etc.
    usage: /analyse-credits