name: PluginAnalyse
version: 1.4
main: de.hackv0gel.pluginAnalyse.PluginAnalyse
author: HackV0gel
website: https://durchlasten.world
commands:
  analyse:
    description: Analyzes packets
    usage: /analyse <view|clear|credits|checkethanol>
  analyse-credits:
    description: Display the Credits from the Developer etc.
    usage: /analyse-credits